### ISSUE TITLE
Activity has leaked Service Connection

### ISSUE THREAD

**Issue by PrinceBE** [AgoraIO/Agora-Android-Tutorial-1to1#16]
On End Call facing This issue.Activity has leaked ServiceConnection android.bluetooth.BluetoothHeadset$2@8e9cc7f that was originally bound here. 
Other than everything working fine. 

Full Log :

: Activity com.zybertron.zoechat.activity.VideoChatViewActivity has leaked IntentReceiver io.agora.rtc.internal.ConnectionChangeBroadcastReceiver@9ea4ec5 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                       android.app.IntentReceiverLeaked: Activity com.zybertron.zoechat.activity.VideoChatViewActivity has leaked IntentReceiver io.agora.rtc.internal.ConnectionChangeBroadcastReceiver@9ea4ec5 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                           at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1159)
                                                                           at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:946)
                                                                           at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1302)
                                                                           at android.app.ContextImpl.registerReceiver(ContextImpl.java:1282)
                                                                           at android.app.ContextImpl.registerReceiver(ContextImpl.java:1276)
                                                                           at io.agora.rtc.internal.RtcEngineImpl.doMonitorSystemEvent(RtcEngineImpl.java:584)
                                                                           at io.agora.rtc.internal.RtcEngineImpl.joinChannel(RtcEngineImpl.java:609)
                                                                           at com.zybertron.zoechat.activity.VideoChatViewActivity.acceptStatic(VideoChatViewActivity.java:166)
                                                                           at com.zybertron.zoechat.activity.VideoChatViewActivity.onMessageEvent(VideoChatViewActivity.java:1060)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
                                                                           at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501)
                                                                           at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
12-15 13:23:35.424 25703-25703/com.zybertron.zoechat E/ActivityThread: Activity com.zybertron.zoechat.activity.VideoChatViewActivity has leaked ServiceConnection android.bluetooth.BluetoothHeadset$2@43b3925 that was originally bound here
                                                                       android.app.ServiceConnectionLeaked: Activity com.zybertron.zoechat.activity.VideoChatViewActivity has leaked ServiceConnection android.bluetooth.BluetoothHeadset$2@43b3925 that was originally bound here
                                                                           at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1336)
                                                                           at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1231)
                                                                           at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1450)
                                                                           at android.app.ContextImpl.bindServiceAsUser(ContextImpl.java:1430)
                                                                           at android.bluetooth.BluetoothHeadset.doBind(BluetoothHeadset.java:305)
                                                                           at android.bluetooth.BluetoothHeadset.<init>(BluetoothHeadset.java:298)
                                                                           at android.bluetooth.BluetoothAdapter.getProfileProxy(BluetoothAdapter.java:1919)
                                                                           at io.agora.rtc.internal.AudioRoutingController.initialize(AudioRoutingController.java:549)
                                                                           at io.agora.rtc.internal.RtcEngineImpl.<init>(RtcEngineImpl.java:221)
                                                                           at io.agora.rtc.RtcEngine.create(RtcEngine.java:21)
                                                                           at com.zybertron.zoechat.activity.VideoChatViewActivity.initializeAgoraEngine(VideoChatViewActivity.java:954)
                                                                           at com.zybertron.zoechat.activity.VideoChatViewActivity.initAgoraEngineAndJoinChannel(VideoChatViewActivity.java:705)
                                                                           at com.zybertron.zoechat.activity.VideoChatViewActivity.onCreate(VideoChatViewActivity.java:564)
                                                                           at android.app.Activity.performCreate(Activity.java:6672)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
                                                                           at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by guohai** [comment]
If you create agora rtc engine in onCreate, you need to destroy it onDestory

**Comment by ashish-jain-db** [comment]
I have done that already but still the issue exists, it's an ANR and issue is a big problem coz if it stucks in one phone running broadcasting using agora sdk, other who are watching that broadcast are also got jammed and app stop responding. Please suggest a resolution
