### ISSUE TITLE
AudioRoutingController Issue

### ISSUE THREAD

**Issue by PrinceBE** [AgoraIO/Agora-Android-Tutorial-1to1#22]
When two client call at the same time app getting crashed and i am getting this type of error in logcat in which it is mentioned its an audio routing controller issue in sdk side.
Expecting your reply asap.

03-03 12:53:28.748 9631-9631/com.hore.hore E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.hore.hore, PID: 9631
                                                             java.lang.NullPointerException: Attempt to invoke virtual method 'void io.agora.rtc.internal.AudioRoutingController.sendEvent(int, int)' on a null object reference
                                                                 at io.agora.rtc.internal.RtcEngineImpl$AgoraPhoneStateListener$1.run(RtcEngineImpl.java:146)
                                                                 at android.os.Handler.handleCallback(Handler.java:751)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by guohai** [comment]
@PrinceBE What version are you with?

**Comment by PrinceBE** [comment]
The version i am using is  'io.agora.rtc:full-sdk:2.0.0'

**Comment by PrinceBE** [comment]
fixed this issue? Expecting your reply asap.

**Comment by guohai** [comment]
We are working on it, same as internal issue #MS-372.

Could you please give us more details if you can reproduce this issue. Thanks.

And will let you know if resolved.

**Comment by PrinceBE** [comment]
The Issue is not happening With the latest Version You released but facing another other check issue #26 Please Check it.
